USE DVDLibrary
GO

IF EXISTS(SELECT * FROM sys.tables WHERE name='DVD')
	DROP TABLE DVD
GO

CREATE TABLE DVD (
	DVDId INT PRIMARY KEY IDENTITY(0,1) NOT NULL,
	Title NVARCHAR(50) NOT NULL,
	Director VARCHAR(32) NULL,
	Rating VARCHAR(5) NULL,
	Notes NVARCHAR(240) NULL,
	ReleaseYear VARCHAR(4) NOT NULL
)


